### ISSUE TITLE
Process automation

### ISSUE THREAD

**Issue by Mystike30** [hardiepiennar/feko_vsh#1]
Hello,

If I understand correctly your code is used to retrieve data from the output files and to represent the different results such as the far field. (http://hardiepienaar.com/2017/11/10/vector-spherical-harmonic-python-tools-for-feko/)

So for a large number of antennas, you have to simulate manually on feko and then use this code to retrieve the data or there is also an automation process so that you don't necessarily have to simulate each antenna manually ?

Thanks in advance.

**Comment by hardiepiennar** [comment]
Unfortunately,  the automation code does not exist. Personally, I used feko’s lua scripting environment to automate the simulation, export and external calculations. I would recommend calling a bash or python script from lua(feko) to do all the heavy lifting. Is this for SKA work?

**Comment by Mystike30** [comment]
Sorry, I don't know what "SKA work" means.

Is it possible to automate the creation of antennas, the simulation and the saving of results? How does it work? 

Thanks in advance.

**Comment by hardiepiennar** [comment]
Yes, yes and yes. FEKO has probably transitioned to python during the past few years. So I would recommend going through their scripting docs. I don't have access FEKO anymore.

**Comment by Mystike30** [comment]
OK thank you !
